# Generated by Django 3.2.9 on 2021-11-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_added_on',
            field=models.DateField(verbose_name='%m/%d/%Y'),
        ),
    ]
