# Generated by Django 3.2.9 on 2021-11-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_alter_item_item_added_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_added_on',
        ),
    ]
